config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :shares do
    resource :map
  end

  resources :charges

  resources :clips
  root to: "shares#index"

end

app/models/clip.rb
class Clip < ActiveRecord::Base
	has_and_belongs_to_many :shares

	def to_param
    text.delete('#')
  end
  
end

app/models/share.rb
class Share < ActiveRecord::Base
	has_attached_file :picture, 
	styles: { medium: "300x300>" },
	:storage => :s3,
	:s3_credentials => {
		:bucket => 'beardstagram',
		:access_key_id => Rails.application.secrets.s3_access_key_id,
		:secret_access_key => Rails.application.secrets.s3_secret_access_key_id
	}


  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\Z/
  has_and_belongs_to_many :clips
  belongs_to :user

  def clip_list
  end

  def clip_list=(some_clips)
  	return if some_clips.empty?

 		some_clips.downcase.split(', ').uniq.each do |clip|
 			self.clips << Clip.find_or_create_by(text: clip)
 		end
 	end

 	def price_calc
 		self.price = 0 if self.price == nil
 		self.price.to_i * 100
 	end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :shares
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

	def new
		@share = Share.find(params[:id])
	end

	def create
	  @share = Share.find(params[:id])
	  @amount = @share.price_calc

	  customer = Stripe::Customer.create(
	    :email => 'example@stripe.com',
	    :card  => params[:stripeToken]
	  )

	  charge = Stripe::Charge.create(
	    :customer    => customer.id,
	    :amount      => @amount,
	    :description => 'Rails Stripe customer',
	    :currency    => 'gbp'
	  )

	rescue Stripe::CardError => e
	  flash[:error] = e.message
	  redirect_to charges_path
	end
end

app/controllers/clips_controller.rb
class ClipsController < ApplicationController

	def show
		@clip = Clip.find_by!(text: '#' + params[:id])		
	end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController

def show
	@share = Share.find(params[:share_id])
end

end

app/controllers/shares_controller.rb
class SharesController < ApplicationController

	def index
		@shares = Share.all
	end

	def new
		@share = Share.new
		if !user_signed_in?
			flash[:notice] = "Please sign up to Beardstagram to share pictures"
			redirect_to '/shares'
		end
	end

	def create
		@share = Share.new(params[:share].permit(:title, :picture, :address, :clip_list, :price))
		@share.save
		redirect_to '/shares'
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/clips_helper.rb
module ClipsHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/shares_helper.rb
module SharesHelper
end

app/views/charges/_new.html.erb
<%= form_tag charges_path(id: @share.id) do %>
  <article>
    <label class="amount">
      <span>Amount: <%=@share.price%> </span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" 
          class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="<%=@share.price_calc%>"></script>
<% end %>

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>£<%= @share.price %></strong>!</h2>

app/views/charges/new.html.erb
<%= form_tag charges_path(id: @share.id) do %>
  <article>
    <label class="amount">
      <span>Amount: £<%= share.price %></span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="<%= share.price_calc %>"></script>
<% end %>

app/views/clips/show.html.erb
<h2>Shares clipped with <%= @clip.text %></h2>

<% @clip.shares.each do |share| %>
		<h3><%= share.title %></h3>
		<% if share.picture.present? %>
			<%= image_tag share.picture.url(:medium), class: 'uploaded-pic' %>
		<% end %>
		<p>
		<% share.clips.each do |clip| %>
			<%= link_to clip.text, clip %>
		<% end %>
		</p>
	<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
      <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=true"></script>
    
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

    
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">
       <meta charset="utf-8">
   
    <title>Beardstagram</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
 
    

    <!-- Bootstrap core CSS -->
    <!-- <link href="../../dist/css/bootstrap.min.css" rel="stylesheet"> -->

    <!-- Custom styles for this template -->
    <!-- <link href="jumbotron-narrow.css" rel="stylesheet"> -->

  </head>

  <body>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div class="container">
      <div class="header">
        <ul class="nav nav-pills pull-right">
          <% if user_signed_in? %>
            <li class="active"><a href="/shares/new">New Share</a></li>
            <li><%= link_to "Sign out", destroy_user_session_path(:authenticity_token => form_authenticity_token()), method: :delete %></li>          
              <%else%>
            <li class="active"><a href="/users/sign_up">Sign Up</a></li>
            <li><a href="/users/sign_in">Sign In</a></li>
          <%end%>
        </ul>
        <a href="/shares"><h3 class="text-muted"><%= image_tag('beardstagram.png')%>Beardstagram</h3></a>
      </div>

      <div class="jumbotron">
        <h1>Beardstagram</h1>
        <p class="lead">
          <%= yield %>
        </p>
      </div>


      <div class="footer">
        <p>&copy; Beardstagram 2014</p>
      </div>

    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
<head>
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/maps/show.html.erb
This beard was spotted in <%= @share.address %>

<div id='map'></div>
<script>

	var map = new GMaps({
	      div: '#map',
	      lat: -51.524128,
	      lng: -0.077364
	 });

	GMaps.geocode({
		// to show the actual location, insert <%= @share.address %> into the string
	  address: "Shoreditch High Street, London",
	  callback: function(results, status) {
	    if (status == 'OK') {
	      var latlng = results[0].geometry.location;
	      map.setCenter(latlng.lat(), latlng.lng());
	      map.addMarker({
	        lat: latlng.lat(),
	        lng: latlng.lng()
	      });
	    }
	  }
	});
</script>

app/views/shares/index.html.erb
<% if @shares.any? %>
	<% @shares.each do |share| %>
		<% @share = share %>
		<h3><%= share.title %></h3>
		<p>
			Beard snapped in <%= link_to share.address, share_map_path(share) %>
		</p>
		<% if share.picture.present? %>
			<%= image_tag share.picture.url(:medium), class: 'uploaded-pic' %>
		<% end %>

		<p>

		<% share.clips.each do |clip| %>
			<%= link_to clip.text, clip %>
		<% end %><br>
		£<%=share.price%> <%= render '/charges/new' %>

		</p>

	<% end %>
<% else %>
 No shares
<% end %>

app/views/shares/new.html.erb
<%= form_for @share, :html => { :multipart => true } do |f| %>
	<p>
		<%= f.label :title %><br>
		<%= f.text_field :title %>
	</p>

	<p>
		<%= f.label :picture %>
  	<%= f.file_field :picture %>
	</p>
	<p>
		<%= f.label :address %>
		<%= f.text_field :address %>
	</p>
	<p>
		<%= f.label :clip_list, 'Clips' %>
		<%= f.text_field :clip_list %>
	</p>
	<p>
		<%= f.label :price, 'Sale Price'%>
		<%= f.text_field :price %>
	</p>

	<p>
		<%= f.submit 'Create share' %>
	</p>
<% end %>